name: dlint
title: Dlint
version: 0.15.0
base: core24
summary: A tool for encouraging best and secure Python coding practices
description: |
  Dlint is a tool for encouraging best coding practices and helping ensure
  Python code is secure.
confinement: strict
grade: stable

apps:
  dlint:
    command: bin/snapcraft-preload $SNAP/bin/python3 -m flake8 --select DUO
    plugs:
      - home

parts:
  dlint:
    plugin: python
    source: https://github.com/dlint-py/dlint.git
    source-tag: $CRAFT_PROJECT_VERSION

  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib
    stage-packages:
      - lib32stdc++6
